### ISSUE TITLE
pm publish returns "Not Found: couch returned 404"

### ISSUE THREAD

**Issue by unkani** [PredixDev/MobileExample-WebApp-Sample#5]
I am able to set my api endpoint correctly to my short route, and pm auth correctly as my developer user, but when trying to "pm publish", I get an error "Not Found: couch returned 404".

**Comment by kamal-mann** [comment]
Looks like you are not using the default oatuh account password. Please run the following command and try again:
`cf update-service <service-instance-name> -c '{"oauth_api_username": "pm-api-gateway-oauth", "oauth_api_password": "$pm_api_gw_secret"}'`

**Comment by karnakar** [comment]
i too facing same problem, what is the default oauth account password.  Is there is any way to know all the parameters in "cf update-service <service-instance-name> -c '{"oauth_api_username": "pm-api-gateway-oauth", "oauth_api_password": "$pm_api_gw_secret"}'"

**Comment by kamal-mann** [comment]
@karnakar, there is no default password, it should be what you have used while executing `pm-configure-uaa.sh` script.

**Comment by SatishPCS** [comment]
@kamal-mann I have used the cf update-service command and the output is "OK" . Then I have used "pm publish" still I am getting the same error "Not Found: couch returned 404" . Can you please guide me on how to proceed further

**Comment by karan-goyal** [comment]
@kamal-mann What will be the parameters in "cf update-service -c '{"oauth_api_username": "pm-api-gateway-oauth", "oauth_api_password": "$pm_api_gw_secret"}'

Also, if anyone was able to get past this; please, let me know.
